"""initial_schema

Revision ID: 47bcd72922b2
Revises: 
Create Date: 2026-09-29 10:27:28.970754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bcd72922b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=100), nullable=False),
    sa.Column('application', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by_employee_id', sa.String(length=50), nullable=True),
    sa.Column('performed_by_name', sa.String(length=150), nullable=True),
    sa.Column('role_used', sa.String(length=50), nullable=True),
    sa.Column('target_record_id', sa.String(length=100), nullable=True),
    sa.Column('target_employee_id', sa.String(length=50), nullable=True),
    sa.Column('target_employee_name', sa.String(length=150), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_performed_by_employee_id'), 'audit_logs', ['performed_by_employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_employee_id'), 'audit_logs', ['target_employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('breakfast_additional_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('order_title', sa.String(length=255), nullable=False),
    sa.Column('order_time', sa.String(length=20), nullable=True),
    sa.Column('applicable_employee_snapshot', sa.JSON(), nullable=True),
    sa.Column('applicable_employee_count', sa.Integer(), nullable=False),
    sa.Column('breakfast_items', sa.JSON(), nullable=True),
    sa.Column('common_items', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_additional_orders_business_date'), 'breakfast_additional_orders', ['business_date'], unique=False)
    op.create_index(op.f('ix_breakfast_additional_orders_order_id'), 'breakfast_additional_orders', ['order_id'], unique=True)
    op.create_table('breakfast_daily_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('employee_snapshot', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('breakfast_items', sa.JSON(), nullable=True),
    sa.Column('common_items', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_daily_entries_business_date'), 'breakfast_daily_entries', ['business_date'], unique=True)
    op.create_table('breakfast_fund_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.String(length=150), nullable=False),
    sa.Column('request_date', sa.String(length=10), nullable=False),
    sa.Column('request_time', sa.String(length=20), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('fund_limit', sa.Float(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('expected_balance', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('provided_amount', sa.Float(), nullable=False),
    sa.Column('provided_by', sa.String(length=150), nullable=True),
    sa.Column('provided_at', sa.DateTime(), nullable=True),
    sa.Column('provided_date', sa.String(length=10), nullable=True),
    sa.Column('provided_time', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('provided_note', sa.Text(), nullable=True),
    sa.Column('verified_amount', sa.Float(), nullable=False),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('difference_reported', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_fund_requests_request_id'), 'breakfast_fund_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_breakfast_fund_requests_status'), 'breakfast_fund_requests', ['status'], unique=False)
    op.create_table('breakfast_money_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('transaction_time', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after_transaction', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('expense_category', sa.String(length=50), nullable=False),
    sa.Column('expense_purpose', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_money_transactions_created_at'), 'breakfast_money_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_breakfast_money_transactions_transaction_date'), 'breakfast_money_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_breakfast_money_transactions_transaction_id'), 'breakfast_money_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_breakfast_money_transactions_type'), 'breakfast_money_transactions', ['type'], unique=False)
    op.create_index('ix_money_txn_date_created', 'breakfast_money_transactions', ['transaction_date', 'created_at'], unique=False)
    op.create_table('breakfast_non_participation_periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.String(length=10), nullable=False),
    sa.Column('to_date', sa.String(length=10), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_non_participation_periods_employee_id'), 'breakfast_non_participation_periods', ['employee_id'], unique=False)
    op.create_index(op.f('ix_breakfast_non_participation_periods_from_date'), 'breakfast_non_participation_periods', ['from_date'], unique=False)
    op.create_index(op.f('ix_breakfast_non_participation_periods_period_id'), 'breakfast_non_participation_periods', ['period_id'], unique=True)
    op.create_index(op.f('ix_breakfast_non_participation_periods_to_date'), 'breakfast_non_participation_periods', ['to_date'], unique=False)
    op.create_table('breakfast_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('employee_name', sa.String(length=150), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_order_items_business_date'), 'breakfast_order_items', ['business_date'], unique=False)
    op.create_index(op.f('ix_breakfast_order_items_employee_id'), 'breakfast_order_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_breakfast_order_items_item_id'), 'breakfast_order_items', ['item_id'], unique=True)
    op.create_index(op.f('ix_breakfast_order_items_order_id'), 'breakfast_order_items', ['order_id'], unique=False)
    op.create_table('breakfast_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_employee_id', sa.String(length=50), nullable=False),
    sa.Column('created_by_employee_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_orders_business_date'), 'breakfast_orders', ['business_date'], unique=False)
    op.create_index(op.f('ix_breakfast_orders_order_id'), 'breakfast_orders', ['order_id'], unique=True)
    op.create_table('breakfast_reasons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_custom_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_reasons_code'), 'breakfast_reasons', ['code'], unique=True)
    op.create_table('breakfast_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('employee_response', sa.String(length=20), nullable=False),
    sa.Column('actual_status', sa.String(length=20), nullable=True),
    sa.Column('actual_status_source', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'business_date', name='uq_breakfast_record_emp_date')
    )
    op.create_index(op.f('ix_breakfast_records_business_date'), 'breakfast_records', ['business_date'], unique=False)
    op.create_index(op.f('ix_breakfast_records_employee_id'), 'breakfast_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_breakfast_records_record_id'), 'breakfast_records', ['record_id'], unique=True)
    op.create_index('ix_record_emp_date', 'breakfast_records', ['employee_id', 'business_date'], unique=False)
    op.create_table('breakfast_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cutoff_time', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('auto_lock_enabled', sa.Boolean(), nullable=False),
    sa.Column('breakfast_fund_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('blob_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=150), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_entity_id'), 'files', ['entity_id'], unique=False)
    op.create_index(op.f('ix_files_entity_type'), 'files', ['entity_type'], unique=False)
    op.create_index(op.f('ix_files_file_id'), 'files', ['file_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('public_holidays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holiday_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_holidays_date'), 'public_holidays', ['date'], unique=True)
    op.create_index(op.f('ix_public_holidays_holiday_id'), 'public_holidays', ['holiday_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('is_hard_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('breakfast_participation_type', sa.String(length=50), nullable=False),
    sa.Column('is_hard_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_public_holidays_holiday_id'), table_name='public_holidays')
    op.drop_index(op.f('ix_public_holidays_date'), table_name='public_holidays')
    op.drop_table('public_holidays')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_files_file_id'), table_name='files')
    op.drop_index(op.f('ix_files_entity_type'), table_name='files')
    op.drop_index(op.f('ix_files_entity_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('breakfast_settings')
    op.drop_index('ix_record_emp_date', table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_record_id'), table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_employee_id'), table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_business_date'), table_name='breakfast_records')
    op.drop_table('breakfast_records')
    op.drop_index(op.f('ix_breakfast_reasons_code'), table_name='breakfast_reasons')
    op.drop_table('breakfast_reasons')
    op.drop_index(op.f('ix_breakfast_orders_order_id'), table_name='breakfast_orders')
    op.drop_index(op.f('ix_breakfast_orders_business_date'), table_name='breakfast_orders')
    op.drop_table('breakfast_orders')
    op.drop_index(op.f('ix_breakfast_order_items_order_id'), table_name='breakfast_order_items')
    op.drop_index(op.f('ix_breakfast_order_items_item_id'), table_name='breakfast_order_items')
    op.drop_index(op.f('ix_breakfast_order_items_employee_id'), table_name='breakfast_order_items')
    op.drop_index(op.f('ix_breakfast_order_items_business_date'), table_name='breakfast_order_items')
    op.drop_table('breakfast_order_items')
    op.drop_index(op.f('ix_breakfast_non_participation_periods_to_date'), table_name='breakfast_non_participation_periods')
    op.drop_index(op.f('ix_breakfast_non_participation_periods_period_id'), table_name='breakfast_non_participation_periods')
    op.drop_index(op.f('ix_breakfast_non_participation_periods_from_date'), table_name='breakfast_non_participation_periods')
    op.drop_index(op.f('ix_breakfast_non_participation_periods_employee_id'), table_name='breakfast_non_participation_periods')
    op.drop_table('breakfast_non_participation_periods')
    op.drop_index('ix_money_txn_date_created', table_name='breakfast_money_transactions')
    op.drop_index(op.f('ix_breakfast_money_transactions_type'), table_name='breakfast_money_transactions')
    op.drop_index(op.f('ix_breakfast_money_transactions_transaction_id'), table_name='breakfast_money_transactions')
    op.drop_index(op.f('ix_breakfast_money_transactions_transaction_date'), table_name='breakfast_money_transactions')
    op.drop_index(op.f('ix_breakfast_money_transactions_created_at'), table_name='breakfast_money_transactions')
    op.drop_table('breakfast_money_transactions')
    op.drop_index(op.f('ix_breakfast_fund_requests_status'), table_name='breakfast_fund_requests')
    op.drop_index(op.f('ix_breakfast_fund_requests_request_id'), table_name='breakfast_fund_requests')
    op.drop_table('breakfast_fund_requests')
    op.drop_index(op.f('ix_breakfast_daily_entries_business_date'), table_name='breakfast_daily_entries')
    op.drop_table('breakfast_daily_entries')
    op.drop_index(op.f('ix_breakfast_additional_orders_order_id'), table_name='breakfast_additional_orders')
    op.drop_index(op.f('ix_breakfast_additional_orders_business_date'), table_name='breakfast_additional_orders')
    op.drop_table('breakfast_additional_orders')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_employee_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_performed_by_employee_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
