"""support_historical_records

Revision ID: bdd18bae01e7
Revises: 47bcd72922b2
Create Date: 2026-09-29 14:43:27.922755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd18bae01e7'
down_revision: Union[str, None] = '47bcd72922b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breakfast_records') as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('record_type', sa.String(length=20), server_default='CURRENT', nullable=False))
        batch_op.add_column(sa.Column('snack', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('snack_quantity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('snack_cost', sa.Float(), server_default='0.0', nullable=True))
        batch_op.add_column(sa.Column('fruit', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fruit_quantity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fruit_cost', sa.Float(), server_default='0.0', nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), server_default='0.0', nullable=True))
        batch_op.add_column(sa.Column('paid_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=100), nullable=True))
        batch_op.alter_column('employee_id',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch_op.alter_column('source',
                   existing_type=sa.VARCHAR(length=30),
                   type_=sa.String(length=50),
                   existing_nullable=False)
        batch_op.alter_column('response',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True)
        batch_op.alter_column('employee_response',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True)
        try:
            batch_op.drop_constraint('uq_breakfast_record_emp_date', type_='unique')
        except Exception:
            pass
        batch_op.create_index(op.f('ix_breakfast_records_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(op.f('ix_breakfast_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(op.f('ix_breakfast_records_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_record_type_date', ['record_type', 'business_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_type_date', table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_source_id'), table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_record_type'), table_name='breakfast_records')
    op.drop_index(op.f('ix_breakfast_records_external_reference'), table_name='breakfast_records')
    op.create_unique_constraint('uq_breakfast_record_emp_date', 'breakfast_records', ['employee_id', 'business_date'])
    op.alter_column('breakfast_records', 'employee_response',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('breakfast_records', 'response',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('breakfast_records', 'source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('breakfast_records', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('breakfast_records', 'external_reference')
    op.drop_column('breakfast_records', 'source_id')
    op.drop_column('breakfast_records', 'payment_type')
    op.drop_column('breakfast_records', 'paid_by')
    op.drop_column('breakfast_records', 'total_cost')
    op.drop_column('breakfast_records', 'fruit_cost')
    op.drop_column('breakfast_records', 'fruit_quantity')
    op.drop_column('breakfast_records', 'fruit')
    op.drop_column('breakfast_records', 'snack_cost')
    op.drop_column('breakfast_records', 'snack_quantity')
    op.drop_column('breakfast_records', 'snack')
    op.drop_column('breakfast_records', 'record_type')
    op.drop_column('breakfast_records', 'employee_name')
    # ### end Alembic commands ###
